import Head from 'next/head';
import '../styles/globals.css';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import Layout from '@/components/Layout';
import { fetchAndCacheLogo } from '@/lib/storeLogo';
import {
  queuePosTransaction,
  setupOfflinePosQueueSync,
} from "@/lib/offlinePosQueue";

function installGlobalApiFetchWrapper() {
  if (typeof window === "undefined") return;
  if (window.__inventoryFetchWrapped) return;

  const originalFetch = window.fetch.bind(window);
  window.__inventoryOriginalFetch = originalFetch;

  window.fetch = async (input, init = {}) => {
    const url = typeof input === "string" ? input : input?.url || "";
    const method = (
      init.method ||
      (typeof input !== "string" ? input?.method : "GET") ||
      "GET"
    ).toUpperCase();

    const isApiRequest = url.startsWith("/api/");
    const headers = new Headers(
      init.headers || (typeof input !== "string" ? input?.headers : undefined) || {}
    );

    if (isApiRequest && !headers.has("Authorization")) {
      const token = localStorage.getItem("auth_token");
      if (token) headers.set("Authorization", `Bearer ${token}`);
    }

    const nextInit = { ...init, headers };

    if (
      url === "/api/transactions/transactions" &&
      method === "POST" &&
      typeof navigator !== "undefined" &&
      !navigator.onLine
    ) {
      let payload = {};
      try {
        payload =
          typeof nextInit.body === "string"
            ? JSON.parse(nextInit.body)
            : nextInit.body || {};
      } catch {
        payload = {};
      }

      const queued = queuePosTransaction(payload);
      return new Response(
        JSON.stringify({
          success: true,
          queued: true,
          message: "Offline: transaction queued for sync",
          transaction: {
            ...payload,
            status: payload?.status || "completed",
            externalId: queued.externalId,
          },
        }),
        {
          status: 202,
          headers: { "Content-Type": "application/json" },
        }
      );
    }

    return window.__inventoryOriginalFetch(input, nextInit);
  };

  window.__inventoryFetchWrapped = true;
}

export default function App({
  Component,
  pageProps,
}) {
  const router = useRouter();
  installGlobalApiFetchWrapper();
  
  // Prime the store logo cache on first load
  useEffect(() => {
    fetchAndCacheLogo();
  }, []);

  // Sync queued POS transactions when connectivity returns.
  useEffect(() => {
    if (typeof window === "undefined") return undefined;

    const cleanupSync = setupOfflinePosQueueSync(window.fetch);
    return () => {
      if (cleanupSync) cleanupSync();
    };
  }, []);
  
  // Don't show layout on login and register pages
  const showLayout = !router.pathname.includes('/login') && !router.pathname.includes('/register');

  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="noindex" />
        <meta name="googlebot" content="noindex" />
        <meta name="google" content="notranslate" />
        <meta name="theme-color" content="#000000" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#000000" />
        <meta name="msapplication-config" content="/browserconfig.xml" />
        <title>St Michael’s Invetory app</title>
        <meta name="description" content="Best products at the best prices!" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {showLayout ? (
        <Layout>
          <Component {...pageProps} />
        </Layout>
      ) : (
        <Component {...pageProps} />
      )}
    </>
  );
}

